apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 418330022238-bsdjcickrj6albsvmjm886rg3v2lutm9.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://31.97.239.39.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
