apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLUlVa05tYl9JWGV4ZUhldkVMc0p6bWhrcXlHOGo= # Base64 for google key
  NEXTAUTH_SECRET: MnAzem5sTjdjME0yVEdQR3ZRWUlaUHFlWWlaTDVwU3VuOCszbXNqckpKaz0= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5Q0JkWHJLOWV2cFRpeVpWblQzYVpwSUk1RW1tMWdLa0tz # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: SGltYW5zaGlAMTE=  # Base64 for admin@123
